# Week3授業前課題
この課題の目的

- 数式演算ライブラリのnumpyに慣れる
- 機械学習に必須な行列演算に慣れる

## 【課題1】 内積を手計算しよう

以下のような行列A,Bを考えます。

$$
A = \left[
    \begin{array}{ccc}
      -1 & 2 & 3 \\
      4 & -5 & 6 \\
      7 & 8 & -9
    \end{array}
  \right],
  B = \left[
    \begin{array}{ccc}
      0 & 2 & 1 \\
      0 & 2 & -8 \\
      2 & 9 & -1
    \end{array}
  \right]
$$

行列の内積A\*Bを手計算で解きなさい。

$    
A * B =
\begin{bmatrix}
-1 & 2 & 3 \\\ 
4 & -5 & 6 \\\
7 & 8 & -9\end{bmatrix}
\hspace{2mm}*\hspace{2mm}
\begin{bmatrix}
0 & 2 & 1 \\\ 
0 & 2 & -8 \\\
2 & 9 & -1
\end{bmatrix}
$

$
\hspace{11mm}=
\begin{bmatrix}
(-1) \times 0 + 2 \times 0 + 3 \times 2 & (-1) \times 2 + 2 \times 2 + 3 \times 9 & (-1) \times 1 + 2 \times (-8) + 3 \times (-1)\\\ 
4 \times 0 + (-5) \times 0 + 6 \times 2 & 4 \times 2 + (-5) \times 2 + 6 \times 9 & 4 \times 1 + (-5) \times (-8) + 6 \times (-1) \\\
7 \times 0 + 8 \times 0 + (-9) \times 2 & 7 \times 2 + 8 \times 2 + (-9) \times 9 & 7 \times 1 + 8 \times (-8) + (-9) \times (-1)
\end{bmatrix}   
$

$
\hspace{11mm}=
\begin{bmatrix}
6 & 29 & -20 \\\ 
12 & 52 & 38 \\\
-18 & -51 & -48
\end{bmatrix}
$

## 【課題2】 1次元配列の内積をfor文で計算しよう

これ以降の課題はNumPyを使って解いてください。

【課題1】では手計算してもらいました。一つ一つの演算はさほど難しくありませんが、演算数は多くかなり面倒くさかったと思います。

この演算をpythonを使って実装するとどうなるのでしょうか？

手計算する際には、まず行列Aの1行目と行列Bの1列目に注目したと思います。そして、

- 行列Aの(0,0)の要素と行列Bの(0,0)の要素を掛け合わせる
- 行列Aの(0,1)の要素と行列Bの(1,0)の要素を掛け合わせる
- 行列Aの(0,2)の要素と行列Bの(2,0)の要素を掛け合わせる
- それらの値を全て足し合わせる
というフローを得て、ようやく一つ目の要素が求まるわけです。

次の要素を計算するには、行列のindexを増やし、上の過程を再度繰り返して行けば良いわけです。下図のようなイメージですね。

![](image/image3_1.png)

まずは、ご自身で配列のindexを指定し、

- 行列Aの(0,0)の要素と行列Bの(0,1)の要素を掛け合わせる
- 行列Aの(0,1)の要素と行列Bの(1,1)の要素を掛け合わせる
- 行列Aの(0,2)の要素と行列Bの(2,1)の要素を掛け合わせる
それらの値を全て足し合わせる
のフローをfor文を使って計算してください。

In [1]:
import numpy as np

#行列A、行列Bを作成
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

#初期値を設定
total = 0

#行列Aの(0, i)と行列Bの(i, 0)を掛け合わせ、足し合わせる
for i in range(3):
    total += A[0, i] * B[i, 0]

#出力
print(total)

6


## 【課題3】 多次元配列の内積をfor文で計算しよう

【課題2】ではA\*Bの(0,0)だけ計算するコードを実装してもらいましたが、全要素を求めるにはどうしたら良いでしょうか？

行列A\*Bの(0,1)を求めるには

行列Aのインデックスは固定（0行目を選択したまま）で、行列Bのインデックスを0列目から1列目に指定しなおせば良いわけです。理解できない方は、手計算でのフローを思い出してください！

- 行列Aの(0,0)の要素と行列Bの(0,1)の要素を掛け合わせる
- 行列Aの(0,1)の要素と行列Bの(1,1)の要素を掛け合わせる
- 行列Aの(0,2)の要素と行列Bの(2,1)の要素を掛け合わせる
- 1、2、3で求めた値を足し合わせる

とすればA\*Bの(0,1)の要素が求まります。

このように同じ計算を順次インデックスを増やして行けば、全要素の計算ができます。

計算の処理自体は全て同じなので、指定する要素の場所をなんとか効率よくできないかというところで登場するのが、for文です。

説明はここまでになります。

for文を使って行列A、Bの積を計算しましょう！【課題2】では(0,0)のみ計算していただきましたが、全て計算してください。

>ヒント  
indexの移行は行方向と列方向があるので、【課題2】で実装していただいたコードに加えて、さらに2回for文が必要になります。



In [2]:
#要素が全て0, 3行, 3列の2次元配列を作成
np_zeros = np.zeros((3, 3))

#A*Bの(0, 0), (0, 1), ..., (2, 2)の要素を計算し、np_zerosに代入
for i in range(3):
    for j in range(3):
        for k in range(3):
            np_zeros[i, j] += A[i, k] * B[k, j]

#出力
np_zeros

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

## 【課題4】 内積をnp.dotで計算しよう

【課題3】ではfor文を使うことで、内積を計算していただきましたが、行列の内積演算の度にこのようにfor文の処理を何回も実装しなくてもはならないのでしょうか？

当然そんなことはなく、実はみなさんがやっていただいた処理はnumpyのメソッドですでに用意されています。

np.dot(A,B)と計算すると、【課題3】で計算していただいたことが一瞬でできます。

np.dot(A,B)を計算して、【課題3】と同じになることを試してください。

In [3]:
AB = np.dot(A, B)
AB

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【課題5】 内積ができないときはどうするか

以下のような例を考えます。

$$
A = \left[
    \begin{array}{ccc}
      -1 & 2 & 3 \\
      4 & -5 & 6 
    \end{array}
  \right],
  B = \left[
    \begin{array}{ccc}
       -9 & 8 & 7 \\
      6 & -5 & 4 
    \end{array}
  \right]
$$

行列A\*Bを計算しようとすると、エラーが出て計算できません。なぜエラーが出るのか理由を記載してください。

そして、行列A、Bのどちらかにある操作をするとエラーが出ずに計算できます。

自分である操作を施し、内積を計算してください。

内積の計算は、左側(行列A)の行ベクトルの要素数と、右側(行列B)の列ベクトルの要素数が等しい時に計算が可能である。   
そのため、どちらかを転置することでこの要素数を揃えることができ、内積の計算ができる。

In [4]:
#行列A, Bを作成
A = np.array([[-1, 2, 3], [4, -5, 6]])
B = np.array([[-9, 8, 7], [6, -5, 4]])

#行列Aを転置し、内積を計算
AB_error = np.dot(A.T, B)
AB_error

array([[ 33, -28,   9],
       [-48,  41,  -6],
       [  9,  -6,  45]])

week2授業前課題は以上になります。内積の演算、np.dot()の便利さを体感していただいかと思います。行列の演算は複数の変数間のかけ算をfor文を使うことなく一気に計算できるので、科学計算にはよく使われます。当然機械学習にもです。

また【課題5】を通じて、どんな行列でも内積が計算できるわけではないことを理解していただいたかと思います。内積計算するための行列形状はアルゴリズムをスクラッチ実装する上で重要です。意図的に内積を計算するために転置を施すという技術もよく使うことになるので，覚えておきましょう！