# Week3授業前課題
この課題の目的

- 数式演算ライブラリのnumpyに慣れる
- 機械学習に必須な行列演算に慣れる

## 【課題1】 内積を手計算しよう

$    
A * B =
\begin{bmatrix}
-1 & 2 & 3 \\\ 
4 & -5 & 6 \\\
7 & 8 & -9\end{bmatrix}
\hspace{2mm}*\hspace{2mm}
\begin{bmatrix}
0 & 2 & 1 \\\ 
0 & 2 & -8 \\\
2 & 9 & -1
\end{bmatrix}
$

$
\hspace{11mm}=
\begin{bmatrix}
(-1) \times 0 + 2 \times 0 + 3 \times 2 & (-1) \times 2 + 2 \times 2 + 3 \times 9 & (-1) \times 1 + 2 \times (-8) + 3 \times (-1)\\\ 
4 \times 0 + (-5) \times 0 + 6 \times 2 & 4 \times 2 + (-5) \times 2 + 6 \times 9 & 4 \times 1 + (-5) \times (-8) + 6 \times (-1) \\\
7 \times 0 + 8 \times 0 + (-9) \times 2 & 7 \times 2 + 8 \times 2 + (-9) \times 9 & 7 \times 1 + 8 \times (-8) + (-9) \times (-1)
\end{bmatrix}   
$

$
\hspace{11mm}=
\begin{bmatrix}
6 & 29 & -20 \\\ 
12 & 52 & 38 \\\
-18 & -51 & -48
\end{bmatrix}
$

## 【課題2】 1次元配列の内積をfor文で計算しよう

In [1]:
import numpy as np

#行列A、行列Bを作成
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

#初期値を設定
total = 0

#行列Aの(0, i)と行列Bの(i, 0)を掛け合わせ、足し合わせる
for i in range(3):
    total += A[0, i] * B[i, 0]

#出力
print(total)

6


## 【課題3】 多次元配列の内積をfor文で計算しよう

In [2]:
#要素が全て0, 3行, 3列の2次元配列を作成
np_zeros = np.zeros((3, 3))

#A*Bの(0, 0), (0, 1), ..., (2, 2)の要素を計算し、np_zerosに代入
for i in range(3):
    for j in range(3):
        for k in range(3):
            np_zeros[i, j] += A[i, k] * B[k, j]

#出力
np_zeros

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

## 【課題4】 内積をnp.dotで計算しよう

In [3]:
AB = np.dot(A, B)
AB

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【課題5】 内積ができないときはどうするか

内積の計算は、左側(行列A)の行ベクトルの要素数と、右側(行列B)の列ベクトルの要素数が等しい時に計算が可能である。   
そのため、どちらかを転置することでこの要素数を揃えることができ、内積の計算ができる。

In [4]:
#行列A, Bを作成
A = np.array([[-1, 2, 3], [4, -5, 6]])
B = np.array([[-9, 8, 7], [6, -5, 4]])

#行列Aを転置し、内積を計算
AB_error = np.dot(A.T, B)
AB_error

array([[ 33, -28,   9],
       [-48,  41,  -6],
       [  9,  -6,  45]])